Support specifying socket fd for connection.
ansible/pylibssh pull request #343
Opened 2022-07-01 02:05 UTC by sabedevops

##### SUMMARY

The libssh library advertises "[Your sockets: the app hands over the socket, or uses libssh sockets](https://www.libssh.org/features/)".

The pylibssh library should support this capability. With respect to Ansible, it opens the door for new connections plugins to seamlessly operate over different sockets  (like Unix sockets, or  WebSockets) while allowing for code reuse.

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```python
import socket

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s = Session()
s.connect(fd=sock.fileno())
```

2022-08-30 13:09 UTC, sabedevops commented
Is there anything I can do to improve this PR?

2022-09-06 14:24 UTC, sabedevops commented
Is there anything I can do that would help get this PR accepted?

2022-09-09 17:18 UTC, Qalthos requested changes

2022-09-09 17:18 UTC, Qalthos commented on src/pylibsshext/session.pyx
> +        cdef int value_fd
We don't actually need this, you can just reuse `value_int`. These are just here to stuff `value` in to the correctly typed C variable so that libssh's `ssh_options_set` knows what to do with them.
```suggestion
```

2022-09-09 17:18 UTC, Qalthos commented on src/pylibsshext/session.pyx
> +        elif key == "gssapi_delegate_credentials":
Likewise, we're not doing anything in particular in this method other than getting the Python input to match libssh's conventions, so there isn't any reason to keep these apart.
```suggestion
        if key in ("fd", "gssapi_delegate_credentials"):
```

2022-09-09 19:31 UTC, sabedevops commented on src/pylibsshext/session.pyx
> +        cdef int value_fd
Thanks for the suggestions @Qalthos. I didn't know that applying the suggestions would auto-resolve the conversation here. I appreciate you taking the time to review this change.

2022-09-12 13:13 UTC, Qalthos approved these changes

2022-09-12 13:31 UTC, merged